import { createApp } from "vue";
import App from "./App.vue";
import "./tailwind.css";
import "./style.css";
import "./admin.css";
import "./settings.css";
import "./layout.css";
import "./icons.css";
import "./profile.css";
import "./studio.css";
import "./control-panel.css";
import "./server-settings.css";
import "./members.css";
import "./community-settings.css";
import "./community-profile.css";
import "./roles.css";
import "./channel-settings.css";
import "./social-profile.css";
import "./self-profile.css";
import "./emoji.css";
import "./brand-refresh.css";
import "./design-v2.css";
import "./home.css";
import "./cosmetics.css";
import "./mini-decoration.css";
import "./design-v3.css";
createApp(App).mount("#app");
